<%@ page language="java" contentType="text/xml; charset=UTF-8"
    pageEncoding="UTF-8"%>
<people>
	<person>
		<name>김학생</name>
		<gender>여</gender>
		<addr>부산</addr>
	</person>
	<person>
		<name>이학생</name>
		<gender>여</gender>
		<addr>부산</addr>
	</person>
	<person>
		<name>박학생</name>
		<gender>여</gender>
		<addr>부산</addr>
	</person>
</people>